version: '3.1'
services:
  mariadb:
    image: 'mariadb:11.0'
    container_name: e_learning_mariadb
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${MARIADB_DB_NAME}'
      - 'MYSQL_USER=${MARIADB_DB_USER}'
      - 'MYSQL_PASSWORD=${MARIADB_DB_USER_PASSWORD}'
    ports:
      - '3306:3306'

  webserver:
    image: 'nginx:alpine'
    container_name: e_learning_webserver
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '1001:80'

  php-fpm:
    build: phpdocker/php-fpm
    container_name: e_learning_fpm
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    container_name: e_learning_phpmyadmin
    ports:
      - '1002:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=e_learning_mariadb

  mailer:
    container_name: e_learning_mailer
    image: schickling/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'

